### ISSUE TITLE
Portainer.io Template.

### ISSUE THREAD

**Issue by ss-o** [ss-o/wg-dash#33]
I have dnscrypt-proxy + pi.hole with match templates below. Also few new features. Will add as soon as able to find spear time.

### Discussed in https://github.com/ss-o/wg-dash/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **voodoopt** July 30, 2021</sup>
Hi thanks for sharing your GIT

Here I add my experience with Portainer.io
With this code in the custom template, I was able to get everything working

```
version: "2.1"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=100
      - PGID=101
      - TZ=America/New_York
      - PEERS=1
    volumes:
      - wg-conf:/config
      - wg-modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
  wg:
    image: ssod/wg-dash
    container_name: wg-dash
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - wg-conf:/etc/wireguard # Recommended mount point
    restart: unless-stopped
volumes:
  wg-conf:
    external: false
  wg-modules:
    external: false
  wgui-db:
    external: false
```
For me the only things that are missing
-> connection status
-> total traffic
As an example the WireGuard Manager (perara/wg-manager)
</div>
